// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:680485486359:web:9139efd34a7c569864c152',
    messagingSenderId: '680485486359',
    projectId: 'taskease-73767',
    authDomain: 'taskease-73767.firebaseapp.com',
    storageBucket: 'taskease-73767.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMmpNlroTdYSNWdBuqYp0jB6_SKqfxDMA',
    appId: '1:680485486359:android:4ce072d3d4bfbe4364c152',
    messagingSenderId: '680485486359',
    projectId: 'taskease-73767',
    storageBucket: 'taskease-73767.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuMG5Qz5Aoz89G5kYKrudcLs1yKnI1UDY',
    appId: '1:680485486359:ios:0ffa619fd834bf3564c152',
    messagingSenderId: '680485486359',
    projectId: 'taskease-73767',
    storageBucket: 'taskease-73767.appspot.com',
    iosClientId: '680485486359-p2hag7ue8bq9gq0qmpgo7dvubnncchgr.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuMG5Qz5Aoz89G5kYKrudcLs1yKnI1UDY',
    appId: '1:680485486359:ios:056a42ff2d7f22e364c152',
    messagingSenderId: '680485486359',
    projectId: 'taskease-73767',
    storageBucket: 'taskease-73767.appspot.com',
    iosClientId: '680485486359-ip8l77qov61iio4d16u3otpgcm47n1u1.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskease.RunnerTests',
  );
}
